[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "smartclean"
version = "1.0.0"
description = "An intelligent Python library for automated data cleaning."
readme = "README.md"
requires-python = ">=3.10"

authors = [
    { name = "Yash Talati" }
]

license = { text = "MIT" }

keywords = [
    "data-cleaning",
    "data-cleaning-library",
    "machine-learning",
    "data-preprocessing",
    "eda",
    "automation",
    "python",
    "pandas"
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]

dependencies = [
    "numpy>=2.0.0",
    "pandas>=2.0.0",
    "matplotlib>=3.7.0",
    "scikit-learn>=1.3.0",
]

[tool.setuptools]
packages = ["smartclean"]