class ReportGenerator:

    def generate(self, profile, decisions, cleaned_df):

        lines = []

        lines.append("=" * 60)
        lines.append("                 SMARTCLEAN CLEANING REPORT")
        lines.append("=" * 60)
        lines.append("")

        original_rows, original_cols = profile["shape"]
        cleaned_rows, cleaned_cols = cleaned_df.shape

        rows_removed = original_rows - cleaned_rows
        cols_removed = original_cols - cleaned_cols

        # ==========================================================
        # DATASET SUMMARY
        # ==========================================================

        lines.append("DATASET SUMMARY")
        lines.append("-" * 60)
        lines.append(f"Original Shape        : {profile['shape']}")
        lines.append(f"Cleaned Shape         : {cleaned_df.shape}")
        lines.append(f"Rows Removed          : {rows_removed}")
        lines.append(f"Columns Removed       : {cols_removed}")
        lines.append("")

        # ==========================================================
        # MISSING VALUES
        # ==========================================================

        lines.append("MISSING VALUE STRATEGY")
        lines.append("-" * 60)

        if decisions["missing"]:

            lines.append(f"{'Column':<30}{'Missing':>10}    Strategy")
            lines.append("-" * 60)

            for column, strategy in decisions["missing"].items():

                missing_count = profile["missing_values"].get(column, 0)

                strategy = strategy.replace("_", " ").title()

                lines.append(
                    f"{column:<30}{missing_count:>10}    {strategy}"
                )

        else:

            lines.append("No missing values detected.")

        lines.append("")

        # ==========================================================
        # DUPLICATES
        # ==========================================================

        lines.append("DUPLICATE HANDLING")
        lines.append("-" * 60)

        duplicate_strategy = decisions.get("duplicates")

        duplicate_count = profile.get("duplicates", 0)

        if duplicate_strategy:

            duplicate_strategy = duplicate_strategy.replace(
                "_",
                " "
            ).title()

            lines.append(f"Duplicate Rows        : {duplicate_count}")
            lines.append(f"Strategy              : {duplicate_strategy}")

        else:

            lines.append("No duplicate rows detected.")

        lines.append("")

        # ==========================================================
        # OUTLIERS
        # ==========================================================

        lines.append("OUTLIER HANDLING")
        lines.append("-" * 60)

        if decisions["outliers"]:

            lines.append(
                f"{'Column':<25}{'Detected':>10}    Strategy"
            )

            lines.append("-" * 60)

            for column, strategy in decisions["outliers"].items():

                detected_count = (
                    profile["outlier_summary"]
                    .get(column, {})
                    .get("count", 0)
                )

                strategy = strategy.replace("_", " ").title()

                lines.append(
                    f"{column:<25}{detected_count:>10}    {strategy}"
                )

        else:

            lines.append("No outliers detected.")

        lines.append("")

        # ==========================================================
        # CLEANING SUMMARY
        # ==========================================================

        lines.append("CLEANING SUMMARY")
        lines.append("-" * 60)

        lines.append(
            f"Missing Columns       : {len(decisions['missing'])}"
        )

        lines.append(
            f"Outlier Columns       : {len(decisions['outliers'])}"
        )

        lines.append(
            f"Duplicate Handling    : {'Enabled' if duplicate_strategy else 'Not Required'}"
        )

        lines.append(
            f"Total Rows Removed    : {rows_removed}"
        )

        lines.append(
            f"Total Columns Removed : {cols_removed}"
        )

        lines.append("")

        lines.append("Status                : SUCCESS")

        lines.append("")
        lines.append("=" * 60)
        lines.append("Generated by SmartClean")
        lines.append("=" * 60)

        return "\n".join(lines)