from ..core.profiler import DataProfiler
from ..core.decision_engine import DecisionEngine
from ..core.execution_engine import ExecutionEngine
from ..core.cleaning_result import CleaningResult
from ..core.report_genrator import ReportGenerator
from ..config.cleaning_config import DEFAULT_CONFIG
from ..utils.missing_normalizer import MissingValueNormalizer


class Cleaner:

    def __init__(self, config=None):

        if config is None:
            self.config = DEFAULT_CONFIG
        else:
            self.config = config

    def clean(self, df):

        # Validate input
        if df is None:
            raise ValueError("Input must be a pandas DataFrame.")

        # Handle completely empty DataFrame
        if df.empty and df.shape[1] == 0:

            report = (
                "============================================================\n"
                "                 SMARTCLEAN CLEANING REPORT\n"
                "============================================================\n\n"
                "DATASET SUMMARY\n"
                "------------------------------------------------------------\n"
                "Original Shape        : (0, 0)\n"
                "Cleaned Shape         : (0, 0)\n\n"
                "Nothing to clean.\n\n"
                "Status                : SUCCESS\n\n"
                "============================================================\n"
                "Generated by SmartClean\n"
                "============================================================"
            )

            return CleaningResult(
                cleaned_df=df.copy(),
                report=report
            )

        # -------------------------------
        # Normalize missing value placeholders
        # -------------------------------
        if self.config["missing_normalization"]["enabled"]:

            df = MissingValueNormalizer.normalize(
                df=df,
                placeholders=self.config["missing_normalization"]["placeholders"]
            )

        # -------------------------------
        # Profiling
        # -------------------------------
        profiler = DataProfiler(df.copy())
        profile = profiler.profile()

        # -------------------------------
        # Decision Engine
        # -------------------------------
        decision_engine = DecisionEngine(
            profile=profile,
            config=self.config
        )

        decisions = decision_engine.generate_decisions()

        # -------------------------------
        # Execution
        # -------------------------------
        executor = ExecutionEngine(
            dataframe=df.copy(),
            decisions=decisions
        )

        cleaned_df = executor.execute()

        # -------------------------------
        # Report
        # -------------------------------
        report_generator = ReportGenerator()

        report = report_generator.generate(
            profile,
            decisions,
            cleaned_df
        )

        return CleaningResult(
            cleaned_df=cleaned_df,
            report=report
        )